2021-01-18 13:22:04,477 INFO    MainThread:17996 [wandb_setup.py:_flush():70] setting env: {}
2021-01-18 13:22:04,477 INFO    MainThread:17996 [wandb_setup.py:_flush():70] multiprocessing start_methods=spawn
2021-01-18 13:22:04,477 INFO    MainThread:17996 [wandb_setup.py:_flush():70] setting login settings: {}
2021-01-18 13:22:04,477 INFO    MainThread:17996 [wandb_init.py:_log_setup():318] Logging user logs to C:\Users\vigne\Desktop\Final-Year-Project\SV\A2C_PPO\wandb\run-20210118_132204-1alaplsy\logs\debug.log
2021-01-18 13:22:04,477 INFO    MainThread:17996 [wandb_init.py:_log_setup():319] Logging internal logs to C:\Users\vigne\Desktop\Final-Year-Project\SV\A2C_PPO\wandb\run-20210118_132204-1alaplsy\logs\debug-internal.log
2021-01-18 13:22:10,529 INFO    MainThread:17996 [wandb_run.py:_console_start():1308] atexit reg
2021-01-18 13:22:10,530 INFO    MainThread:17996 [wandb_run.py:_redirect():1175] redirect: SettingsConsole.WRAP
2021-01-18 13:22:10,531 INFO    MainThread:17996 [wandb_run.py:_redirect():1206] Wrapping output streams.
2021-01-18 13:22:10,531 INFO    MainThread:17996 [wandb_run.py:_redirect():1222] Redirects installed.
2021-01-18 13:22:11,584 INFO    MainThread:17996 [wandb_run.py:_atexit_cleanup():1278] got exitcode: 1
2021-01-18 13:22:11,584 INFO    MainThread:17996 [wandb_run.py:_restore():1250] restore
2021-01-18 13:22:11,901 INFO    MainThread:17996 [wandb_run.py:_wait_for_finish():1395] got exit ret: uuid: "d122ca15db23488f993911e78dc59e40"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 747
      total_bytes: 747
    }
  }
}

2021-01-18 13:22:13,905 INFO    MainThread:17996 [wandb_run.py:_wait_for_finish():1395] got exit ret: uuid: "80e6f9dc62a743e7b5e7f30cd35fa0f3"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 4905
      total_bytes: 4905
    }
  }
}

2021-01-18 13:22:15,288 INFO    MainThread:17996 [wandb_run.py:_show_files():1614] logging synced files
2021-01-18 13:22:15,292 INFO    MainThread:17996 [internal.py:handle_exit():139] Internal process exited
